### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by madhugit2022** [oci-labs/meta-opendds#18]
Hi ,

I get the following compiler errors in both 3.20 and 3.14 in yocto. 

| ../../tao/PortableServer/Object_SArgument_T.cpp:117:1:   required from here
| ../../tao/Any_Insert_Policy_T.h:44:14: error: 'void CORBA::Any::operator<<=(unsigned char)' is private within this context
|    44 |         (*p) <<= x;
|       |         ~~~~~^~~~~
| In file included from ../../tao/PortableServer/POAManagerC.h:46,
|                  from ../../tao/PortableServer/Object_Adapter.h:29,
|                  from ../../tao/PortableServer/Root_POA.h:27,
|                  from Servant_Base.cpp:5:
| ../../tao/AnyTypeCode/Any.h:171:10: note: declared private here
|   171 |     void operator<<= (unsigned char);
|       |          ^~~~~~~~
| ../../tao/Any_Insert_Policy_T.h:44:14: error: invalid conversion from 'CORBA::Object*' to 'unsigned char' [-fpermissive]
|    44 |         (*p) <<= x;
|       |         ~~~~~^~~~~
|       |              |
|       |              CORBA::Object*

I had checked out from github directly and made changes to bb for SHA1 of OCI_TAO alone and started compiling using bitbake opendds and got the error

**Comment by jwillemsen** [comment]
You need ACE 7.0.8 and TAO 3.0.8 to get this to work, there is a pending PR to upgrade to that release on github master, see https://github.com/objectcomputing/OpenDDS/pull/3587

**Comment by madhugit2022** [comment]
Hi Johnny,

Thanks for the reply. I tried patching the configure file with the one above and still get the same error. Can you please let me know is there any other way for this? I am trying to get the opendds up on Kirkstone.

**Comment by jwillemsen** [comment]
Have you removed the ACE tree before running configure again, when there is a tree it will not redownload ACE

**Comment by madhugit2022** [comment]
I had deleted the entire opendds directory  before compiling. It downloaded the source code again

**Comment by madhugit2022** [comment]
It worked after setting ACE to 7.0.8 as @jwillemsen  suggested. thanks
