### ISSUE TITLE
DEPENDS needed?

### ISSUE THREAD

**Issue by mitza-oci** [oci-labs/meta-opendds#3]
DEPENDS at the top of recipes-connectivity/opendds/opendds.inc lists glib and boost, but these shouldn't be needed unless optional components within OpenDDS are enabled in the configure script.

**Comment by kdopen** [comment]
Which options require them? Generally it is better to have an unneeded DEPEND that a missing one. Since Rocko, the latter will break the build, and it would need to be clearly documented else anyone creating a BBAPPEND won't know what to add if they decide to use one of these options.

**Comment by mitza-oci** [comment]
> Which options require them? 

- Boost is only needed for a pre-C++11 compiler building the ishapes GUI (Qt would have to be available)
- GLib is only needed when building the wireshark dissector

I wouldn't expect either of these to be part of an embedded target.

More info here:
https://github.com/objectcomputing/OpenDDS/blob/master/docs/dependencies.md

**Comment by kdopen** [comment]
OK will look into these

**Comment by kdopen** [comment]
Dependencies removed in Warrior branch
